### PR TITLE
wait for operator before deploying crs

### PR DESCRIPTION
**Pull request by pb82**
Wait for the prometheus operator to be ready (and finish deployment of it's CRDs) before continuing to install Prometheus and Alertmanager.

Fixes https://github.com/integr8ly/application-monitoring-operator/issues/24

Verification steps:
1. Use a fresh cluster where the images have not been pulled yet
1. Use a namespace called `application-monitoring` or change the namespace here: https://github.com/integr8ly/application-monitoring-operator/blob/master/deploy/roles/prometheus-operator-clusterrole_binding.yaml#L12
1. Run the operator locally (or deploy it) against this namespace and create the ApplicationMonitoring CR: `oc create -f deploy/examples/ApplicationMonitoring.yaml`
1. None of the Operators should fail and the stack should be deployed

### CODE REVIEW

**Comment by david-martin** [comment]
Using minishift locally, I'm hitting some errors in the application-monitoring-operator logs.
https://gist.github.com/david-martin/287e65f5b1eede02f29732cb272ea29a
I'll look into this more, but seems like a permission issue

**Comment by grdryn** [comment]
I see that route hose issue on master (I haven't deployed this PR).

**Comment by grdryn** [comment]
I might try to check if more logging here would give more info: https://github.com/integr8ly/application-monitoring-operator/blob/master/pkg/controller/applicationmonitoring/applicationmonitoring_controller.go#L288..L290

Alternatively, maybe using `github.com/openshift/api/route/v1` rather than the current more loosely-typed implementation might help?

**Comment by grdryn** [comment]
```
{"level":"info","ts":1557919806.6345694,"logger":"controller_applicationmonitoring","caller":"applicationmonitoring/applicationmonitoring_controller.go:291","msg":"Spec=map[port:map[targetPort:web] tls:map[termination:Reencrypt] to:map[kind:Service name:prometheus-service] wildcardPolicy:None]"}
```

It has everything but the `host`. :thinking:

**Comment by grdryn** [comment]
> I think I'll have a PR shortly to fix this route host issue.

See #38

**Comment by pb82** [comment]
@grdryn We don't set the host value in the template, we let OpenShift do that. It's still a mystery to me why this works sometimes and sometimes doesn't. But i'll give your PR a try.

**Comment by pb82** [comment]
@david-martin could you retry this please? @grdryn 's changes are applied now and this should fix the problem reading back the host value.

**Comment by pb82** [comment]
@david-martin When / how did the image registry change from where Grafana and Prometheus are pulled? The pull secret is somethinng we recently had to deal with for fuse and it's handled in the installer. We likely need to do the same here. But i agree that we should have general instructions for how to set this up independent of the installer.

**Comment by grdryn** [comment]
> I ran the operator locally and used v0.8.0 of the operator-sdk to avoid this issue operator-framework/operator-sdk#1329,
so you may want to build with that before pushing a new release of the image to quay.

Do you guys have any process or guidelines around moving to a new version of the operator-sdk?

**Comment by grdryn** [comment]
I also hit that issue with pulling from registry.redhat.io, but I just replaced the image references with the upstream ones from quay.io/docker.io

**Comment by david-martin** [comment]
> When / how did the image registry change from where Grafana and Prometheus are pulled

@pb82 
* Grafana: https://github.com/integr8ly/application-monitoring-operator/pull/31
* OAuth Proxy (for prometheus): https://github.com/integr8ly/application-monitoring-operator/pull/30
* OAuth Proxy (for alertmanager): https://github.com/integr8ly/application-monitoring-operator/pull/36

**Comment by pb82** [comment]
@david-martin merging this and dealing with the readme update for the pull secret and the sdk update in another PR

**Pull request merged**
