### PR TITLE
update prometheus resource links

### PR DESCRIPTION
**Pull request by laurafitzgerald**
**Why**
Prometheus Operator CRDs file names have [changed](https://github.com/coreos/prometheus-operator/tree/master/example/prometheus-operator-crd).

**Verification**
Install - there should be no `server reported 404 Not Found, status code=404` seen

### CODE REVIEW

**Comment by R-Lawton** [comment]
Ill verify this since Peter is out on PTO

**Comment by laurafitzgerald** [comment]
@david-martin sure I can do that. We also import crds from the Grafana Operator. To be consistent should we also do it for those resources?

**Comment by david-martin** [comment]
@laurafitzgerald Yes, let's do those too

**Comment by laurafitzgerald** [comment]
Hey @david-martin turns out the file names have changed since v0.34.0 of the prometheus operator. So if we're locking the version down, we need to stick with the older version of the file name. When we update the version, the file names would then need to be updated. Do you still want to go ahead with fixing the version?

**Comment by david-martin** [comment]
> Do you still want to go ahead with fixing the version

Yes, locking it down now while we're familiar with the problem makes sense.

**Comment by laurafitzgerald** [comment]
@david-martin @R-Lawton This is pr is ready for review again. I did ask a more general question about the templates for grafana/prometheus in [chat](https://chat.google.com/room/AAAAEIV2uTo/U2l5qooA_58) but trying to keep this change small for now.

**Comment by david-martin** [comment]
Thanks @laurafitzgerald

**Pull request merged**
