### PR TITLE
Operator Lifecycle Manager configuration

### PR DESCRIPTION
**Pull request by davidkirwan**
JIRA: https://issues.jboss.org/browse/INTLY-2349
PR(s): 
- https://github.com/integr8ly/manifests/pull/64
- https://github.com/integr8ly/integreatly-operator/pull/106

Adding the OLM Configuration for 0.0.25, 0.0.26

### CODE REVIEW

**Comment by david-martin** [comment]
@StevenTobin would you mind taking a look at this when you have time?

**Comment by davidkirwan** [comment]
@david-martin the corresponding PR at https://github.com/integr8ly/manifests/pull/64 has been merged, mind approving ?

**Comment by david-martin** [comment]
@davidkirwan merged. Worth doing a release with new tag?

**Comment by davidkirwan** [comment]
Hmm I think we can probably wait until the next code change which will take this in, but there is nothing in this PR which actually affects the code etc, its just the location where the files get stored when we are creating new versions of the "application" for quay.

**Pull request merged**
